Fix: Cross DB operation error
The cross DB operation is throwing a TypeError because `window.crossDbOperation` is not a function.  This commit addresses the error.